# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'Ubuntu-20.04'

container: jedbrown/petsc-root:latest

steps:
- script: |
    make info
  displayName: 'make info'
- script: |
    make
  displayName: 'make'
- script: |
    make junit realsearch=%
  displayName: 'junit'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/*.junit'
    mergeTestResults: true
    failTaskOnFailedTests: true
