[workspace]
members = [
        "rust/libceed",
        "rust/libceed-sys",
        "examples/rust/ex1-volume",
        "examples/rust/ex2-surface",
        "examples/rust/ex3-vector-volume",
        "examples/rust/ex4-vector-surface",
        "examples/rust/mesh",
]
