#[build]
#target = "nvptx64-nvidia-cuda"  # default compilation target

[target.nvptx64-nvidia-cuda]
rustflags = [
  "-C", "linker-plugin-lto",
  "-C", "target-cpu=sm_80",
]
[unstable]
build-std = ["panic_abort","core", "alloc"]
