#[build]
#target = "nvptx64-nvidia-cuda"  # Set default compilation target

# Target-specific rustflags
[target.nvptx64-nvidia-cuda]
rustflags = [
  "-C", "embed-bitcode=yes",    # Embed LLVM bitcode
  "-C", "target-cpu=sm_80",     # Specify NVIDIA SM80 architecture
  "-Z", "dylib-lto",            # Enable LTO for dynamic libraries
]
#linker = "echo"
