name: C/Fortran - Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v5
    - name: Install LCOV
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov llvm valgrind
    - name: Set compiler
      run: |
        case "${{ matrix.compiler }}" in
          gcc)
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
            echo "FC=gfortran" >> $GITHUB_ENV
            echo "GCOV=gcov" >> $GITHUB_ENV
            ;;
          clang)
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
            echo "FC=" >> $GITHUB_ENV
            echo "GCOV=llvm-cov --gcov-tool gcov" >> $GITHUB_ENV
            # Test that the default compiler works at runtime
            echo "CEED_CPU_JIT_CXX=" >> $GITHUB_ENV
            ;;
        esac
    - name: Show compiler version
      run: $CC --version | head -1
    - name: Build and test libCEED
      env:
        OPT: -O2 -g -ffp-contract=fast
        COVERAGE: 1
      run: |
        make info
        NUM_JOBS=$(getconf _NPROCESSORS_ONLN)
        # Note: set CEED_CPU_JIT_CXX here to ensure value is stored in the binary
        CEED_CPU_JIT_CXX="$CXX" make -j$NUM_JOBS
        make JUNIT_BATCH="${{ matrix.os }}-${{ matrix.compiler }}" junit -j$NUM_JOBS
    - name: Collect coverage
      run: |
        lcov --directory . --capture --gcov-tool $GCOV --output-file coverage.info --no-external --exclude '/usr/include/*' --rc geninfo_unexecuted_blocks=1 --verbose --demangle-cpp --substitute 's#(^|/)(?!tests/)([^/]+)/(t[^/]+-f\.[^/]+)$#$1$2/tests/$3#g' --substitute 's#([^/]+)/(?<!examples/ceed/)(ex[^/]+-f\.[^/]+)$#$1/examples/ceed/$2#g' --ignore-errors inconsistent --ignore-errors unused,unused
    - name: Codecov upload
      uses: codecov/codecov-action@v5
      with:
        files: coverage.info
        plugins: noop
        token: ${{ secrets.CODECOV_TOKEN }}
