name: IBM Power

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v5
    - name: Install cross toolchain and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static gcc-powerpc64le-linux-gnu gfortran-powerpc64le-linux-gnu
    - name: Build libCEED for ppc64le
      env:
        CC: powerpc64le-linux-gnu-${{ matrix.compiler }}
        FC: powerpc64le-linux-gnu-gfortran
        OPT: -O2 -g -ffp-contract=fast
      run: |
        make info
        make -j4
    - name: Test libCEED under QEMU
      env:
        CC: powerpc64le-linux-gnu-${{ matrix.compiler }}
        FC: powerpc64le-linux-gnu-gfortran
        OPT: -O2 -g -ffp-contract=fast
        CEED_TEST_RUNNER: qemu-ppc64le -L /usr/powerpc64le-linux-gnu
      run: |
        qemu-ppc64le -L /usr/powerpc64le-linux-gnu build/t000-ceed /cpu/self/ref/serial
        make -j4 PROVE_OPTS=-j4 prove
