name: ARM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v4
    - name: Build and test libCEED
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran
      run: |
        make info
        make -j
        make prove -j
