name: IBM Power

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc]
        arch: [ppc64le]
        distro: [ubuntu22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v4
    - name: Hardware setup and test libCEED
      uses: uraimo/run-on-arch-action@v3
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        run: |
          apt-get -y update
          apt-get install -y build-essential
          apt-get install -y gfortran
          apt-get install -y python3
          uname -a
          make info
          make -j
          make prove -j search="t5 ex"
