name: Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-26.04]
        compiler: [gcc]
        python-version: ['3.x']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v5
    - name: PETSc install
      run: |
        sudo apt-get update
        sudo apt install -y python3-pip python3 libpetsc-real-dev python3-mpi4py python3-petsc4py
    - name: Python dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Python test
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran
      run: |
        make info
        make -j2
        export CEED_DIR=$PWD
        pip install .
        cd python/tests
        PYTHON=python3 make test TEST_OPTS="--ceed /cpu/self/ref/serial -vv"
        cd ../../examples/python
        PYTHON=python3 make test TEST_OPTS="--ceed /cpu/self/ref/serial -vv"
        cd ../..
    - name: Python style
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran
      run: |
        make format-py && git diff --exit-code
    - name: Python version
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran
      run: |
        make vermin
